/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    plans: Plan;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en') | ('ru' | 'en')[];
  globals: {
    header: Header;
    home: Home;
    'tariffs-page': TariffsPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    'tariffs-page': TariffsPageSelect<false> | TariffsPageSelect<true>;
  };
  locale: 'ru' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Подписки на странице тарифов, сгруппированные по продуктовым линиям.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: string;
  /**
   * Определяет вкладку на странице тарифов.
   */
  line: 'meet' | 'webinar' | 'messenger' | 'mail' | 'drive' | 'boards';
  /**
   * Карточка «Бесплатно»: слева, без цены, с блоком «Содержит продукты».
   */
  isTrial?: boolean | null;
  /**
   * Карточка справа: вместо цены показывается «По запросу».
   */
  priceOnRequest?: boolean | null;
  /**
   * Центральная карточка в цвете линии: такие тарифы переключаются в ней как варианты одного тарифа.
   */
  highlighted?: boolean | null;
  order: number;
  /**
   * Так тариф называется в списке и на карточке.
   */
  name: string;
  /**
   * Итоговая сумма за период — её и увидит покупатель.
   */
  prices?:
    | {
        duration: '3' | '6' | '12';
        price: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Итоговая цена = базовая сумма + цена за единицу × количество.
   */
  unit?: {
    /**
     * Текст слева от счётчика: «Пользователей мессенджера».
     */
    label?: string | null;
    min?: number | null;
    max?: number | null;
    step?: number | null;
    /**
     * С каким числом открывается карточка.
     */
    defaultCount?: number | null;
    /**
     * Сумма за период при выбранном количестве — она уже итоговая.
     */
    unitRates?:
      | {
          duration: '3' | '6' | '12';
          unitPrice: number;
          fixedPrice: number;
          id?: string | null;
        }[]
      | null;
  };
  features?:
    | {
        text: string;
        /**
         * Жирная часть после текста: «от 5 ГБ», «100».
         */
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Иконки продуктов внутри пробной карточки.
   */
  products?:
    | {
        icon?:
          | (
              | 'none'
              | 'meetings'
              | 'webinar'
              | 'messenger'
              | 'mail'
              | 'drive'
              | 'boards'
              | 'ai-assistant'
              | 'online-broadcasts'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  ctaSecondary?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?: {
    relationTo: 'plans';
    value: string | Plan;
  } | null;
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  line?: T;
  isTrial?: T;
  priceOnRequest?: T;
  highlighted?: T;
  order?: T;
  name?: T;
  prices?:
    | T
    | {
        duration?: T;
        price?: T;
        id?: T;
      };
  unit?:
    | T
    | {
        label?: T;
        min?: T;
        max?: T;
        step?: T;
        defaultCount?: T;
        unitRates?:
          | T
          | {
              duration?: T;
              unitPrice?: T;
              fixedPrice?: T;
              id?: T;
            };
      };
  features?:
    | T
    | {
        text?: T;
        value?: T;
        id?: T;
      };
  products?:
    | T
    | {
        icon?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  ctaSecondary?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Верхняя полоса шапки на десктопе. На мобильной версии те же данные — в меню под бургером.
   */
  topbar?: {
    /**
     * Для ссылки tel: берутся только цифры и «+»; без цифр телефон не выводится.
     */
    phone?: string | null;
    /**
     * На сайте выводится ссылкой mailto:.
     */
    email?: string | null;
    /**
     * Иконка — только из набора: произвольную картинку задать нельзя.
     */
    links?:
      | {
          label: string;
          href: string;
          icon?: ('none' | 'search' | 'phone' | 'book') | null;
          id?: string | null;
        }[]
      | null;
  };
  logo: string | Media;
  logoHref?: string | null;
  title: string;
  menu?:
    | {
        label: string;
        /**
         * Можно оставить пустым: тогда пункт только раскрывает подменю, как «Продукты» и «Отрасли».
         */
        href?: string | null;
        /**
         * Иконка пункта в нижней навигации на мобильной версии.
         */
        mobileIcon?: ('subscriptions' | 'industries' | 'blog' | 'events') | null;
        /**
         * На десктопе раскрывается панелью под шапкой, на мобильной — шторкой снизу.
         */
        children?:
          | {
              label: string;
              description?: string | null;
              icon?:
                | (
                    | 'none'
                    | 'meetings'
                    | 'webinar'
                    | 'messenger'
                    | 'mail'
                    | 'drive'
                    | 'boards'
                    | 'ai-assistant'
                    | 'online-broadcasts'
                  )
                | null;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * На мобильной версии корзина выводится иконкой, а вход — коротким текстом, если он задан.
   */
  actions?: {
    cart?: {
      label?: string | null;
      href?: string | null;
    };
    login?: {
      label?: string | null;
      shortLabel?: string | null;
      href?: string | null;
    };
    register?: {
      label?: string | null;
      href?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  /**
   * Первый экран главной: слайдер и полоса бейджей под ним.
   */
  hero?: {
    /**
     * Слайды переключаются автоматически, стрелками и точками под ними.
     */
    slides?:
      | {
          /**
           * Лучше всего смотрится заголовок до 80 символов.
           */
          title: string;
          description?: string | null;
          image: string | Media;
          /**
           * Быстрые ссылки на продукты под заголовком. Цвет чипа задаётся иконкой продукта.
           */
          chips?:
            | {
                label: string;
                href: string;
                icon?:
                  | (
                      | 'none'
                      | 'meetings'
                      | 'webinar'
                      | 'messenger'
                      | 'mail'
                      | 'drive'
                      | 'boards'
                      | 'ai-assistant'
                      | 'online-broadcasts'
                    )
                  | null;
                id?: string | null;
              }[]
            | null;
          cta?: {
            label?: string | null;
            href?: string | null;
          };
          ctaSecondary?: {
            label?: string | null;
            href?: string | null;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Отдельная картинка под каждую ширину: на мобильной документы идут столбиком, на десктопе — в строку.
     */
    badgeStrip?: {
      mobile?: (string | null) | Media;
      tablet?: (string | null) | Media;
      desktop?: (string | null) | Media;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Вкладки, периоды оплаты и блок консультации. Карточки тарифов — в коллекции «Тарифы».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tariffs-page".
 */
export interface TariffsPage {
  id: string;
  title: string;
  /**
   * Порядок вкладок на странице тарифов.
   */
  lines?:
    | {
        /**
         * Должен совпадать с продуктовой линией тарифов.
         */
        key: 'meet' | 'webinar' | 'messenger' | 'mail' | 'drive' | 'boards';
        label: string;
        /**
         * Глиф продукта в цвете линии.
         */
        icon?: ('meet' | 'webinar' | 'chat' | 'mail' | 'disk' | 'boards') | null;
        /**
         * Маленький бейдж «AI» над вкладкой.
         */
        withAi?: boolean | null;
        /**
         * Для линий, которые ещё не продаются.
         */
        disabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Переключатель периода на странице тарифов.
   */
  durations?:
    | {
        months: number;
        /**
         * Печатается в переключателе периода; у первого периода не показывается.
         */
        discount?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Тёмная карточка под карточками тарифов.
   */
  consultation?: {
    /**
     * Без заголовка блок на сайте не выводится.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Если не заполнен, телефона в блоке не будет.
     */
    phone?: string | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  topbar?:
    | T
    | {
        phone?: T;
        email?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              icon?: T;
              id?: T;
            };
      };
  logo?: T;
  logoHref?: T;
  title?: T;
  menu?:
    | T
    | {
        label?: T;
        href?: T;
        mobileIcon?: T;
        children?:
          | T
          | {
              label?: T;
              description?: T;
              icon?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  actions?:
    | T
    | {
        cart?:
          | T
          | {
              label?: T;
              href?: T;
            };
        login?:
          | T
          | {
              label?: T;
              shortLabel?: T;
              href?: T;
            };
        register?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        slides?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              chips?:
                | T
                | {
                    label?: T;
                    href?: T;
                    icon?: T;
                    id?: T;
                  };
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              ctaSecondary?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
            };
        badgeStrip?:
          | T
          | {
              mobile?: T;
              tablet?: T;
              desktop?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tariffs-page_select".
 */
export interface TariffsPageSelect<T extends boolean = true> {
  title?: T;
  lines?:
    | T
    | {
        key?: T;
        label?: T;
        icon?: T;
        withAi?: T;
        disabled?: T;
        id?: T;
      };
  durations?:
    | T
    | {
        months?: T;
        discount?: T;
        id?: T;
      };
  consultation?:
    | T
    | {
        title?: T;
        text?: T;
        phone?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}